services:
  postgres:
    image: postgres:16
    container_name: linkcart-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?must be set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?must be set}
      POSTGRES_DB: ${POSTGRES_DB:?must be set}
    ports:
      - "5432:5432"
    volumes:
      - linkcart-postgres-data:/var/lib/postgresql/data

volumes:
  linkcart-postgres-data:
