spring:
  application:
    name: linkcart-backend
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=300s

server:
  port: 8080

springdoc:
  api-docs:
    path: /openapi.json
  swagger-ui:
    path: /docs
